@Host = https://localhost:44345/api/liberary

GET {{Host}}/authors
Accept: application/json

###

GET {{Host}}/authors/3
Accept: application/json

###

GET {{Host}}/books
Accept: application/json

###

POST {{Host}}/authors HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "firstName": "Mohammed",
    "lastName": "Abdelhay 3"
}

###

POST {{Host}}/authors HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "firstName": "Yahya",
    "lastName": "Mohammed 3"
}

###

POST {{Host}}/books HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "title": "C# Advanced 3",
  "authorId": 3
}

###

POST {{Host}}/books HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "title": "C# is WAYN 3",
  "authorId": 4
}

###

POST {{Host}}/books HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "title": "C# in Real world Apps 3",
  "authorId": 3
}

###
